runtime: python3.11
memory_size: 512
timeout: 900  # 15 minutes for batch processing
handler: lambda_function.lambda_handler
description: "One-time migration to add editorData field to existing medical histories"
environment_variables:
  AWS_REGION: "us-east-1"
