runtime: python3.11
memory_size: 512
timeout: 30
handler: lambda_function.lambda_handler
description: "Get all patients for a doctor with medical history counts"
environment_variables:
  HISTORIES_TABLE: "medical-histories"
  PATIENTS_TABLE: "pacients"
  AWS_REGION: "us-east-1"
