runtime: python3.11
memory_size: 512
timeout: 60
handler: lambda_function.lambda_handler
description: Process example clinical history and save doctor to DynamoDB (Step 2)
environment_variables:
  AWS_REGION: "us-east-1"
  DYNAMODB_DOCTORS_TABLE: "doctors"
  EXTRACT_FORMAT_LAMBDA: "extract_format"
