runtime: python3.11
memory_size: 512
timeout: 30
handler: lambda_function.lambda_handler
description: "Get medical histories for a doctor with filters and pagination"
environment_variables:
  DYNAMODB_TABLE: "medical-histories"
  AWS_REGION: "us-east-1"
